// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     org/chromium/ui/gfx/BitmapHelper

#ifndef org_chromium_ui_gfx_BitmapHelper_JNI
#define org_chromium_ui_gfx_BitmapHelper_JNI

#include <jni.h>

#include "base/android/jni_android.h"
#include "base/android/scoped_java_ref.h"
#include "base/basictypes.h"
#include "base/logging.h"

using base::android::ScopedJavaLocalRef;

// Step 1: forward declarations.
namespace {
const char kBitmapHelperClassPath[] =
    "org/chromium/ui/gfx/BitmapHelper";
// Leaking this jclass as we cannot use LazyInstance from some threads.
jclass g_BitmapHelper_clazz = NULL;
}  // namespace

namespace gfx {

// Step 2: method stubs.

static base::subtle::AtomicWord g_BitmapHelper_createBitmap = 0;
static ScopedJavaLocalRef<jobject> Java_BitmapHelper_createBitmap(JNIEnv* env,
    jint width,
    jint height) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_BitmapHelper_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, g_BitmapHelper_clazz,
      "createBitmap",

"("
"I"
"I"
")"
"Landroid/graphics/Bitmap;",
      &g_BitmapHelper_createBitmap);

  jobject ret =
    env->CallStaticObjectMethod(g_BitmapHelper_clazz,
      method_id, width, height);
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jobject>(env, ret);
}

static base::subtle::AtomicWord g_BitmapHelper_decodeDrawableResource = 0;
static ScopedJavaLocalRef<jobject>
    Java_BitmapHelper_decodeDrawableResource(JNIEnv* env, jstring name,
    jint reqWidth,
    jint reqHeight) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_BitmapHelper_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, g_BitmapHelper_clazz,
      "decodeDrawableResource",

"("
"Ljava/lang/String;"
"I"
"I"
")"
"Landroid/graphics/Bitmap;",
      &g_BitmapHelper_decodeDrawableResource);

  jobject ret =
    env->CallStaticObjectMethod(g_BitmapHelper_clazz,
      method_id, name, reqWidth, reqHeight);
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jobject>(env, ret);
}

// Step 3: RegisterNatives.

static bool RegisterNativesImpl(JNIEnv* env) {

  g_BitmapHelper_clazz = reinterpret_cast<jclass>(env->NewGlobalRef(
      base::android::GetClass(env, kBitmapHelperClassPath).obj()));
  return true;
}
}  // namespace gfx

#endif  // org_chromium_ui_gfx_BitmapHelper_JNI
