// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     org/chromium/ui/gfx/DeviceDisplayInfo

#ifndef org_chromium_ui_gfx_DeviceDisplayInfo_JNI
#define org_chromium_ui_gfx_DeviceDisplayInfo_JNI

#include <jni.h>

#include "base/android/jni_android.h"
#include "base/android/scoped_java_ref.h"
#include "base/basictypes.h"
#include "base/logging.h"

using base::android::ScopedJavaLocalRef;

// Step 1: forward declarations.
namespace {
const char kDeviceDisplayInfoClassPath[] =
    "org/chromium/ui/gfx/DeviceDisplayInfo";
// Leaking this jclass as we cannot use LazyInstance from some threads.
jclass g_DeviceDisplayInfo_clazz = NULL;
}  // namespace

namespace gfx {

static void UpdateSharedDeviceDisplayInfo(JNIEnv* env, jobject obj,
    jint displayHeight,
    jint displayWidth,
    jint bitsPerPixel,
    jint bitsPerComponent,
    jdouble dipScale,
    jint smallestDIPWidth);

// Step 2: method stubs.

static base::subtle::AtomicWord g_DeviceDisplayInfo_getDisplayHeight = 0;
static jint Java_DeviceDisplayInfo_getDisplayHeight(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_DeviceDisplayInfo_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_DeviceDisplayInfo_clazz,
      "getDisplayHeight",

"("
")"
"I",
      &g_DeviceDisplayInfo_getDisplayHeight);

  jint ret =
    env->CallIntMethod(obj,
      method_id);
  base::android::CheckException(env);
  return ret;
}

static base::subtle::AtomicWord g_DeviceDisplayInfo_getDisplayWidth = 0;
static jint Java_DeviceDisplayInfo_getDisplayWidth(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_DeviceDisplayInfo_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_DeviceDisplayInfo_clazz,
      "getDisplayWidth",

"("
")"
"I",
      &g_DeviceDisplayInfo_getDisplayWidth);

  jint ret =
    env->CallIntMethod(obj,
      method_id);
  base::android::CheckException(env);
  return ret;
}

static base::subtle::AtomicWord g_DeviceDisplayInfo_getBitsPerPixel = 0;
static jint Java_DeviceDisplayInfo_getBitsPerPixel(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_DeviceDisplayInfo_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_DeviceDisplayInfo_clazz,
      "getBitsPerPixel",

"("
")"
"I",
      &g_DeviceDisplayInfo_getBitsPerPixel);

  jint ret =
    env->CallIntMethod(obj,
      method_id);
  base::android::CheckException(env);
  return ret;
}

static base::subtle::AtomicWord g_DeviceDisplayInfo_getBitsPerComponent = 0;
static jint Java_DeviceDisplayInfo_getBitsPerComponent(JNIEnv* env, jobject obj)
    {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_DeviceDisplayInfo_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_DeviceDisplayInfo_clazz,
      "getBitsPerComponent",

"("
")"
"I",
      &g_DeviceDisplayInfo_getBitsPerComponent);

  jint ret =
    env->CallIntMethod(obj,
      method_id);
  base::android::CheckException(env);
  return ret;
}

static base::subtle::AtomicWord g_DeviceDisplayInfo_getDIPScale = 0;
static jdouble Java_DeviceDisplayInfo_getDIPScale(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_DeviceDisplayInfo_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_DeviceDisplayInfo_clazz,
      "getDIPScale",

"("
")"
"D",
      &g_DeviceDisplayInfo_getDIPScale);

  jdouble ret =
    env->CallDoubleMethod(obj,
      method_id);
  base::android::CheckException(env);
  return ret;
}

static base::subtle::AtomicWord g_DeviceDisplayInfo_getSmallestDIPWidth = 0;
static jint Java_DeviceDisplayInfo_getSmallestDIPWidth(JNIEnv* env, jobject obj)
    {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_DeviceDisplayInfo_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_DeviceDisplayInfo_clazz,
      "getSmallestDIPWidth",

"("
")"
"I",
      &g_DeviceDisplayInfo_getSmallestDIPWidth);

  jint ret =
    env->CallIntMethod(obj,
      method_id);
  base::android::CheckException(env);
  return ret;
}

static base::subtle::AtomicWord g_DeviceDisplayInfo_createWithListener = 0;
static ScopedJavaLocalRef<jobject>
    Java_DeviceDisplayInfo_createWithListener(JNIEnv* env, jobject context) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_DeviceDisplayInfo_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, g_DeviceDisplayInfo_clazz,
      "createWithListener",

"("
"Landroid/content/Context;"
")"
"Lorg/chromium/ui/gfx/DeviceDisplayInfo;",
      &g_DeviceDisplayInfo_createWithListener);

  jobject ret =
    env->CallStaticObjectMethod(g_DeviceDisplayInfo_clazz,
      method_id, context);
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jobject>(env, ret);
}

// Step 3: RegisterNatives.

static bool RegisterNativesImpl(JNIEnv* env) {

  g_DeviceDisplayInfo_clazz = reinterpret_cast<jclass>(env->NewGlobalRef(
      base::android::GetClass(env, kDeviceDisplayInfoClassPath).obj()));
  static const JNINativeMethod kMethodsDeviceDisplayInfo[] = {
    { "nativeUpdateSharedDeviceDisplayInfo",
"("
"I"
"I"
"I"
"I"
"D"
"I"
")"
"V", reinterpret_cast<void*>(UpdateSharedDeviceDisplayInfo) },
  };
  const int kMethodsDeviceDisplayInfoSize =
      arraysize(kMethodsDeviceDisplayInfo);

  if (env->RegisterNatives(g_DeviceDisplayInfo_clazz,
                           kMethodsDeviceDisplayInfo,
                           kMethodsDeviceDisplayInfoSize) < 0) {
    LOG(ERROR) << "RegisterNatives failed in " << __FILE__;
    return false;
  }

  return true;
}
}  // namespace gfx

#endif  // org_chromium_ui_gfx_DeviceDisplayInfo_JNI
