// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     org/chromium/components/browser/autofill/PersonalAutofillPopulator

#ifndef org_chromium_components_browser_autofill_PersonalAutofillPopulator_JNI
#define org_chromium_components_browser_autofill_PersonalAutofillPopulator_JNI

#include <jni.h>

#include "base/android/jni_android.h"
#include "base/android/scoped_java_ref.h"
#include "base/basictypes.h"
#include "base/logging.h"

using base::android::ScopedJavaLocalRef;

// Step 1: forward declarations.
namespace {
const char kPersonalAutofillPopulatorClassPath[] =
    "org/chromium/components/browser/autofill/PersonalAutofillPopulator";
// Leaking this jclass as we cannot use LazyInstance from some threads.
jclass g_PersonalAutofillPopulator_clazz = NULL;
}  // namespace

namespace autofill {

// Step 2: method stubs.

static base::subtle::AtomicWord g_PersonalAutofillPopulator_create = 0;
static ScopedJavaLocalRef<jobject> Java_PersonalAutofillPopulator_create(JNIEnv*
    env, jobject context) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_PersonalAutofillPopulator_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, g_PersonalAutofillPopulator_clazz,
      "create",

"("
"Landroid/content/Context;"
")"
"Lorg/chromium/components/browser/autofill/PersonalAutofillPopulator;",
      &g_PersonalAutofillPopulator_create);

  jobject ret =
    env->CallStaticObjectMethod(g_PersonalAutofillPopulator_clazz,
      method_id, context);
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jobject>(env, ret);
}

static base::subtle::AtomicWord g_PersonalAutofillPopulator_getFirstName = 0;
static ScopedJavaLocalRef<jstring>
    Java_PersonalAutofillPopulator_getFirstName(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_PersonalAutofillPopulator_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_PersonalAutofillPopulator_clazz,
      "getFirstName",

"("
")"
"Ljava/lang/String;",
      &g_PersonalAutofillPopulator_getFirstName);

  jstring ret =
    static_cast<jstring>(env->CallObjectMethod(obj,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_PersonalAutofillPopulator_getLastName = 0;
static ScopedJavaLocalRef<jstring>
    Java_PersonalAutofillPopulator_getLastName(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_PersonalAutofillPopulator_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_PersonalAutofillPopulator_clazz,
      "getLastName",

"("
")"
"Ljava/lang/String;",
      &g_PersonalAutofillPopulator_getLastName);

  jstring ret =
    static_cast<jstring>(env->CallObjectMethod(obj,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_PersonalAutofillPopulator_getMiddleName = 0;
static ScopedJavaLocalRef<jstring>
    Java_PersonalAutofillPopulator_getMiddleName(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_PersonalAutofillPopulator_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_PersonalAutofillPopulator_clazz,
      "getMiddleName",

"("
")"
"Ljava/lang/String;",
      &g_PersonalAutofillPopulator_getMiddleName);

  jstring ret =
    static_cast<jstring>(env->CallObjectMethod(obj,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_PersonalAutofillPopulator_getSuffix = 0;
static ScopedJavaLocalRef<jstring>
    Java_PersonalAutofillPopulator_getSuffix(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_PersonalAutofillPopulator_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_PersonalAutofillPopulator_clazz,
      "getSuffix",

"("
")"
"Ljava/lang/String;",
      &g_PersonalAutofillPopulator_getSuffix);

  jstring ret =
    static_cast<jstring>(env->CallObjectMethod(obj,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_PersonalAutofillPopulator_getEmailAddresses =
    0;
static ScopedJavaLocalRef<jobjectArray>
    Java_PersonalAutofillPopulator_getEmailAddresses(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_PersonalAutofillPopulator_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_PersonalAutofillPopulator_clazz,
      "getEmailAddresses",

"("
")"
"[Ljava/lang/String;",
      &g_PersonalAutofillPopulator_getEmailAddresses);

  jobjectArray ret =
    static_cast<jobjectArray>(env->CallObjectMethod(obj,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jobjectArray>(env, ret);
}

static base::subtle::AtomicWord g_PersonalAutofillPopulator_getStreet = 0;
static ScopedJavaLocalRef<jstring>
    Java_PersonalAutofillPopulator_getStreet(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_PersonalAutofillPopulator_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_PersonalAutofillPopulator_clazz,
      "getStreet",

"("
")"
"Ljava/lang/String;",
      &g_PersonalAutofillPopulator_getStreet);

  jstring ret =
    static_cast<jstring>(env->CallObjectMethod(obj,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_PersonalAutofillPopulator_getPobox = 0;
static ScopedJavaLocalRef<jstring>
    Java_PersonalAutofillPopulator_getPobox(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_PersonalAutofillPopulator_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_PersonalAutofillPopulator_clazz,
      "getPobox",

"("
")"
"Ljava/lang/String;",
      &g_PersonalAutofillPopulator_getPobox);

  jstring ret =
    static_cast<jstring>(env->CallObjectMethod(obj,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_PersonalAutofillPopulator_getNeighborhood = 0;
static ScopedJavaLocalRef<jstring>
    Java_PersonalAutofillPopulator_getNeighborhood(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_PersonalAutofillPopulator_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_PersonalAutofillPopulator_clazz,
      "getNeighborhood",

"("
")"
"Ljava/lang/String;",
      &g_PersonalAutofillPopulator_getNeighborhood);

  jstring ret =
    static_cast<jstring>(env->CallObjectMethod(obj,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_PersonalAutofillPopulator_getCity = 0;
static ScopedJavaLocalRef<jstring>
    Java_PersonalAutofillPopulator_getCity(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_PersonalAutofillPopulator_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_PersonalAutofillPopulator_clazz,
      "getCity",

"("
")"
"Ljava/lang/String;",
      &g_PersonalAutofillPopulator_getCity);

  jstring ret =
    static_cast<jstring>(env->CallObjectMethod(obj,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_PersonalAutofillPopulator_getRegion = 0;
static ScopedJavaLocalRef<jstring>
    Java_PersonalAutofillPopulator_getRegion(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_PersonalAutofillPopulator_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_PersonalAutofillPopulator_clazz,
      "getRegion",

"("
")"
"Ljava/lang/String;",
      &g_PersonalAutofillPopulator_getRegion);

  jstring ret =
    static_cast<jstring>(env->CallObjectMethod(obj,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_PersonalAutofillPopulator_getPostalCode = 0;
static ScopedJavaLocalRef<jstring>
    Java_PersonalAutofillPopulator_getPostalCode(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_PersonalAutofillPopulator_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_PersonalAutofillPopulator_clazz,
      "getPostalCode",

"("
")"
"Ljava/lang/String;",
      &g_PersonalAutofillPopulator_getPostalCode);

  jstring ret =
    static_cast<jstring>(env->CallObjectMethod(obj,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_PersonalAutofillPopulator_getCountry = 0;
static ScopedJavaLocalRef<jstring>
    Java_PersonalAutofillPopulator_getCountry(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_PersonalAutofillPopulator_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_PersonalAutofillPopulator_clazz,
      "getCountry",

"("
")"
"Ljava/lang/String;",
      &g_PersonalAutofillPopulator_getCountry);

  jstring ret =
    static_cast<jstring>(env->CallObjectMethod(obj,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_PersonalAutofillPopulator_getPhoneNumbers = 0;
static ScopedJavaLocalRef<jobjectArray>
    Java_PersonalAutofillPopulator_getPhoneNumbers(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_PersonalAutofillPopulator_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_PersonalAutofillPopulator_clazz,
      "getPhoneNumbers",

"("
")"
"[Ljava/lang/String;",
      &g_PersonalAutofillPopulator_getPhoneNumbers);

  jobjectArray ret =
    static_cast<jobjectArray>(env->CallObjectMethod(obj,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jobjectArray>(env, ret);
}

static base::subtle::AtomicWord g_PersonalAutofillPopulator_getHasPermissions =
    0;
static jboolean Java_PersonalAutofillPopulator_getHasPermissions(JNIEnv* env,
    jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_PersonalAutofillPopulator_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_PersonalAutofillPopulator_clazz,
      "getHasPermissions",

"("
")"
"Z",
      &g_PersonalAutofillPopulator_getHasPermissions);

  jboolean ret =
    env->CallBooleanMethod(obj,
      method_id);
  base::android::CheckException(env);
  return ret;
}

// Step 3: RegisterNatives.

static bool RegisterNativesImpl(JNIEnv* env) {

  g_PersonalAutofillPopulator_clazz =
      reinterpret_cast<jclass>(env->NewGlobalRef(
      base::android::GetClass(env, kPersonalAutofillPopulatorClassPath).obj()));
  return true;
}
}  // namespace autofill

#endif  // org_chromium_components_browser_autofill_PersonalAutofillPopulator_JNI
