// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     org/chromium/android_webview/AwFormDatabase

#ifndef org_chromium_android_webview_AwFormDatabase_JNI
#define org_chromium_android_webview_AwFormDatabase_JNI

#include <jni.h>

#include "base/android/jni_android.h"
#include "base/android/scoped_java_ref.h"
#include "base/basictypes.h"
#include "base/logging.h"

using base::android::ScopedJavaLocalRef;

// Step 1: forward declarations.
namespace {
const char kAwFormDatabaseClassPath[] =
    "org/chromium/android_webview/AwFormDatabase";
// Leaking this jclass as we cannot use LazyInstance from some threads.
jclass g_AwFormDatabase_clazz = NULL;
}  // namespace

namespace android_webview {

static jboolean HasFormData(JNIEnv* env, jclass clazz);

static void ClearFormData(JNIEnv* env, jclass clazz);

// Step 2: method stubs.

// Step 3: RegisterNatives.

static bool RegisterNativesImpl(JNIEnv* env) {

  g_AwFormDatabase_clazz = reinterpret_cast<jclass>(env->NewGlobalRef(
      base::android::GetClass(env, kAwFormDatabaseClassPath).obj()));
  static const JNINativeMethod kMethodsAwFormDatabase[] = {
    { "nativeHasFormData",
"("
")"
"Z", reinterpret_cast<void*>(HasFormData) },
    { "nativeClearFormData",
"("
")"
"V", reinterpret_cast<void*>(ClearFormData) },
  };
  const int kMethodsAwFormDatabaseSize = arraysize(kMethodsAwFormDatabase);

  if (env->RegisterNatives(g_AwFormDatabase_clazz,
                           kMethodsAwFormDatabase,
                           kMethodsAwFormDatabaseSize) < 0) {
    LOG(ERROR) << "RegisterNatives failed in " << __FILE__;
    return false;
  }

  return true;
}
}  // namespace android_webview

#endif  // org_chromium_android_webview_AwFormDatabase_JNI
