// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     org/chromium/content/common/DeviceTelephonyInfo

#ifndef org_chromium_content_common_DeviceTelephonyInfo_JNI
#define org_chromium_content_common_DeviceTelephonyInfo_JNI

#include <jni.h>

#include "base/android/jni_android.h"
#include "base/android/scoped_java_ref.h"
#include "base/basictypes.h"
#include "base/logging.h"

using base::android::ScopedJavaLocalRef;

// Step 1: forward declarations.
namespace {
const char kDeviceTelephonyInfoClassPath[] =
    "org/chromium/content/common/DeviceTelephonyInfo";
// Leaking this jclass as we cannot use LazyInstance from some threads.
jclass g_DeviceTelephonyInfo_clazz = NULL;
}  // namespace

// Step 2: method stubs.

static base::subtle::AtomicWord g_DeviceTelephonyInfo_getNetworkCountryIso = 0;
static ScopedJavaLocalRef<jstring>
    Java_DeviceTelephonyInfo_getNetworkCountryIso(JNIEnv* env, jobject obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_DeviceTelephonyInfo_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_DeviceTelephonyInfo_clazz,
      "getNetworkCountryIso",

"("
")"
"Ljava/lang/String;",
      &g_DeviceTelephonyInfo_getNetworkCountryIso);

  jstring ret =
    static_cast<jstring>(env->CallObjectMethod(obj,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_DeviceTelephonyInfo_create = 0;
static ScopedJavaLocalRef<jobject> Java_DeviceTelephonyInfo_create(JNIEnv* env,
    jobject context) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_DeviceTelephonyInfo_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, g_DeviceTelephonyInfo_clazz,
      "create",

"("
"Landroid/content/Context;"
")"
"Lorg/chromium/content/common/DeviceTelephonyInfo;",
      &g_DeviceTelephonyInfo_create);

  jobject ret =
    env->CallStaticObjectMethod(g_DeviceTelephonyInfo_clazz,
      method_id, context);
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jobject>(env, ret);
}

// Step 3: RegisterNatives.

static bool RegisterNativesImpl(JNIEnv* env) {

  g_DeviceTelephonyInfo_clazz = reinterpret_cast<jclass>(env->NewGlobalRef(
      base::android::GetClass(env, kDeviceTelephonyInfoClassPath).obj()));
  return true;
}

#endif  // org_chromium_content_common_DeviceTelephonyInfo_JNI
