// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     org/chromium/content/browser/PowerSaveBlocker

#ifndef org_chromium_content_browser_PowerSaveBlocker_JNI
#define org_chromium_content_browser_PowerSaveBlocker_JNI

#include <jni.h>

#include "base/android/jni_android.h"
#include "base/android/scoped_java_ref.h"
#include "base/basictypes.h"
#include "base/logging.h"

using base::android::ScopedJavaLocalRef;

// Step 1: forward declarations.
namespace {
const char kPowerSaveBlockerClassPath[] =
    "org/chromium/content/browser/PowerSaveBlocker";
// Leaking this jclass as we cannot use LazyInstance from some threads.
jclass g_PowerSaveBlocker_clazz = NULL;
}  // namespace

// Step 2: method stubs.

static base::subtle::AtomicWord g_PowerSaveBlocker_applyBlock = 0;
static void Java_PowerSaveBlocker_applyBlock(JNIEnv* env, jobject view) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_PowerSaveBlocker_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, g_PowerSaveBlocker_clazz,
      "applyBlock",

"("
"Lorg/chromium/ui/base/ViewAndroid;"
")"
"V",
      &g_PowerSaveBlocker_applyBlock);

  env->CallStaticVoidMethod(g_PowerSaveBlocker_clazz,
      method_id, view);
  base::android::CheckException(env);

}

static base::subtle::AtomicWord g_PowerSaveBlocker_removeBlock = 0;
static void Java_PowerSaveBlocker_removeBlock(JNIEnv* env, jobject view) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_PowerSaveBlocker_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, g_PowerSaveBlocker_clazz,
      "removeBlock",

"("
"Lorg/chromium/ui/base/ViewAndroid;"
")"
"V",
      &g_PowerSaveBlocker_removeBlock);

  env->CallStaticVoidMethod(g_PowerSaveBlocker_clazz,
      method_id, view);
  base::android::CheckException(env);

}

// Step 3: RegisterNatives.

static bool RegisterNativesImpl(JNIEnv* env) {

  g_PowerSaveBlocker_clazz = reinterpret_cast<jclass>(env->NewGlobalRef(
      base::android::GetClass(env, kPowerSaveBlockerClassPath).obj()));
  return true;
}

#endif  // org_chromium_content_browser_PowerSaveBlocker_JNI
