// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     org/chromium/content/browser/TouchEventSynthesizer

#ifndef org_chromium_content_browser_TouchEventSynthesizer_JNI
#define org_chromium_content_browser_TouchEventSynthesizer_JNI

#include <jni.h>

#include "base/android/jni_android.h"
#include "base/android/scoped_java_ref.h"
#include "base/basictypes.h"
#include "base/logging.h"

using base::android::ScopedJavaLocalRef;

// Step 1: forward declarations.
namespace {
const char kTouchEventSynthesizerClassPath[] =
    "org/chromium/content/browser/TouchEventSynthesizer";
// Leaking this jclass as we cannot use LazyInstance from some threads.
jclass g_TouchEventSynthesizer_clazz = NULL;
}  // namespace

namespace content {

// Step 2: method stubs.

static base::subtle::AtomicWord g_TouchEventSynthesizer_setPointer = 0;
static void Java_TouchEventSynthesizer_setPointer(JNIEnv* env, jobject obj, jint
    index,
    jint x,
    jint y,
    jint id) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_TouchEventSynthesizer_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_TouchEventSynthesizer_clazz,
      "setPointer",

"("
"I"
"I"
"I"
"I"
")"
"V",
      &g_TouchEventSynthesizer_setPointer);

  env->CallVoidMethod(obj,
      method_id, index, x, y, id);
  base::android::CheckException(env);

}

static base::subtle::AtomicWord g_TouchEventSynthesizer_inject = 0;
static void Java_TouchEventSynthesizer_inject(JNIEnv* env, jobject obj, jint
    action,
    jint pointerCount) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_TouchEventSynthesizer_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_TouchEventSynthesizer_clazz,
      "inject",

"("
"I"
"I"
")"
"V",
      &g_TouchEventSynthesizer_inject);

  env->CallVoidMethod(obj,
      method_id, action, pointerCount);
  base::android::CheckException(env);

}

// Step 3: RegisterNatives.

static bool RegisterNativesImpl(JNIEnv* env) {

  g_TouchEventSynthesizer_clazz = reinterpret_cast<jclass>(env->NewGlobalRef(
      base::android::GetClass(env, kTouchEventSynthesizerClassPath).obj()));
  return true;
}
}  // namespace content

#endif  // org_chromium_content_browser_TouchEventSynthesizer_JNI
