// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     org/chromium/content/browser/TracingControllerAndroid

#ifndef org_chromium_content_browser_TracingControllerAndroid_JNI
#define org_chromium_content_browser_TracingControllerAndroid_JNI

#include <jni.h>

#include "base/android/jni_android.h"
#include "base/android/scoped_java_ref.h"
#include "base/basictypes.h"
#include "base/logging.h"

using base::android::ScopedJavaLocalRef;

// Step 1: forward declarations.
namespace {
const char kTracingControllerAndroidClassPath[] =
    "org/chromium/content/browser/TracingControllerAndroid";
// Leaking this jclass as we cannot use LazyInstance from some threads.
jclass g_TracingControllerAndroid_clazz = NULL;
}  // namespace

namespace content {

static jlong Init(JNIEnv* env, jobject obj);

static jstring GetDefaultCategories(JNIEnv* env, jobject obj);

// Step 2: method stubs.
static void Destroy(JNIEnv* env, jobject obj,
    jlong nativeTracingControllerAndroid) {
  DCHECK(nativeTracingControllerAndroid) << "Destroy";
  TracingControllerAndroid* native =
      reinterpret_cast<TracingControllerAndroid*>(nativeTracingControllerAndroid);
  return native->Destroy(env, obj);
}

static jboolean StartTracing(JNIEnv* env, jobject obj,
    jlong nativeTracingControllerAndroid,
    jstring filename,
    jstring categories,
    jboolean recordContinuously) {
  DCHECK(nativeTracingControllerAndroid) << "StartTracing";
  TracingControllerAndroid* native =
      reinterpret_cast<TracingControllerAndroid*>(nativeTracingControllerAndroid);
  return native->StartTracing(env, obj, filename, categories,
      recordContinuously);
}

static void StopTracing(JNIEnv* env, jobject obj,
    jlong nativeTracingControllerAndroid) {
  DCHECK(nativeTracingControllerAndroid) << "StopTracing";
  TracingControllerAndroid* native =
      reinterpret_cast<TracingControllerAndroid*>(nativeTracingControllerAndroid);
  return native->StopTracing(env, obj);
}

static base::subtle::AtomicWord g_TracingControllerAndroid_onTracingStopped = 0;
static void Java_TracingControllerAndroid_onTracingStopped(JNIEnv* env, jobject
    obj) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_TracingControllerAndroid_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, g_TracingControllerAndroid_clazz,
      "onTracingStopped",

"("
")"
"V",
      &g_TracingControllerAndroid_onTracingStopped);

  env->CallVoidMethod(obj,
      method_id);
  base::android::CheckException(env);

}

// Step 3: RegisterNatives.

static bool RegisterNativesImpl(JNIEnv* env) {

  g_TracingControllerAndroid_clazz = reinterpret_cast<jclass>(env->NewGlobalRef(
      base::android::GetClass(env, kTracingControllerAndroidClassPath).obj()));
  static const JNINativeMethod kMethodsTracingControllerAndroid[] = {
    { "nativeInit",
"("
")"
"J", reinterpret_cast<void*>(Init) },
    { "nativeDestroy",
"("
"J"
")"
"V", reinterpret_cast<void*>(Destroy) },
    { "nativeStartTracing",
"("
"J"
"Ljava/lang/String;"
"Ljava/lang/String;"
"Z"
")"
"Z", reinterpret_cast<void*>(StartTracing) },
    { "nativeStopTracing",
"("
"J"
")"
"V", reinterpret_cast<void*>(StopTracing) },
    { "nativeGetDefaultCategories",
"("
")"
"Ljava/lang/String;", reinterpret_cast<void*>(GetDefaultCategories) },
  };
  const int kMethodsTracingControllerAndroidSize =
      arraysize(kMethodsTracingControllerAndroid);

  if (env->RegisterNatives(g_TracingControllerAndroid_clazz,
                           kMethodsTracingControllerAndroid,
                           kMethodsTracingControllerAndroidSize) < 0) {
    LOG(ERROR) << "RegisterNatives failed in " << __FILE__;
    return false;
  }

  return true;
}
}  // namespace content

#endif  // org_chromium_content_browser_TracingControllerAndroid_JNI
